name: fair-segmentation-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.26.4
  - matplotlib
  - jupyter
  - ome-zarr
  - zarr>=3
  - tifffile
  - scikit-image
  - pip
  - pip:
    - torch>=1.10
    - torchvision>=0.2
    - torchaudio
