name: fair-segmentation-napari-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy>=1.26.4
  - napari==0.6.6
  - matplotlib
  - jupyter
  - ome-zarr
  - zarr>=3
  - tifffile
  - scikit-image
  - pip
  - pip:
#    - git+https://github.com/volume-em/empanada-napari.git@zarr_2dinference
    - git+https://github.com/drstone-genius04/empanada-napari.git@fix/export-shape-assertion-duplicate-deps